baseURL: "www.rpunamiya.dev"
languageCode: "en-us"
title: "Ryan Punamiya"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: photography
#       name: Photography
#       title: Photography
#       url: /photography
#       weight: 1

params:
  title: "Ryan Punamiya"
  description: 
  staticPath: ""  # The path to serve the static files from
  favicon: "bolt-solid.svg"
  useBootstrapCDN: false
  animate: true

  theme:
  
  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName:  # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: false
      disableContact: false

  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ryan Punamiya."
    subtitle: "I think robots are cool"
    content: "Undergraduate Researcher at RL2 Lab under [Prof. Danfei Xu](https://faculty.cc.gatech.edu/~danfei/). I want to build robots that can intelligently learn in any environment."
    image: /images/self.png
    bottomImage:
      enable: true
      roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1LnNgg14ZXwl_xvoYRwlCHMNoopeSg-c2/view?usp=sharing"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ryan-punamiya-47bb5a141/
        - icon: fab fa-github
          url: https://github.com/ryanthecreator
        - icon: fa fa-robot
          url: "https://faculty.cc.gatech.edu/~danfei/"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/self.png"
    content: |-
      I am a second year **_Computer Science_** major (Intelligence + Theory) at **_Georgia Tech_** with a passion for **_robotics_** and **_deep learning_**. I am researching imitation learning for arm robots and the use of LLMs for task planning.

      I am also working on a project that will be used to passively map potholes in a city using swarm computing and big data.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Java"
        - "C++ (ROS)"
        - "HTML/CSS"
        - "Javascript"
        - "Python (Pytorch, OpenCV, rospy)"
        - "Solidworks"

  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Undergraduate Researcher"
        company: "RL2 Lab"
        companyUrl: "https://faculty.cc.gatech.edu/~danfei/"
        date: "Fall 2023 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: "I am working on extending the work of [MimicPlay](https://mimic-play.github.io/) which is in the domain of imitation learning. I am utilizing ROS, Pytorch and OpenCV."
      - job: "Undergraduate Researcher"
        company: "LIDAR Lab - Georgia Tech VIP Program"
        companyUrl: "https://lab-idar.gatech.edu/vip/"
        date: "Spring 2023 - present"
        content: "I am working on quadruped robot perception. I applied a modified DCGAN network to reconstruct occluded 2.5D elevation maps for better path planning." 
      - job: "Data Science/ML Intern"
        company: "Netcore Cloud"
        companyUrl: "https://netcorecloud.com/"
        date: "Summer 2021"
        content: "I applied and contrasted 14 different Deep Learning models to evaluate impact of word choice on email marketing. I worked under [Yogendra Sisodia](https://www.linkedin.com/in/ysisodia/?originalSubdomain=in)"
      - job: "Software Developer"
        company: "Robojackets"
        date: "Fall 2022 - present"
        featuredLink:
          enable: true
          name: "Codebase"
          url: "https://github.com/RoboJackets/urc-rover"
        content: |
          I am working as a member of the software team for the University Rover Challenge. I implemented drone landing and path planning behaviour for the robot
  education:
    enable: true
    index: false
    items:
      - title: "Bachelors of Science in Computer Science (Intelligence + Theory)"
        school:
          name: "Georgia Institute of Technology"
          url: "https://www.cc.gatech.edu/"
        date: "Fall 2022 - Spring 2025"
        GPA: "4.0/4.0"
        content: |-
          - Relevant Coursework: Computer Organization & Programming, Data Structures and Algorithms, Linear Algebra I, II, Multivariable Calculus, Applied Combinatorics
          - External Coursework: Stanford University CS 231N – Deep Learning for Computer Vision
          - Extracurricular Activities:
            - Grand Challenges – Competitive program accepting 200 freshmen, working in groups to solve a global issue
            - Robojackets - Robotics Team Software Member
            - Inventure Prize 2024 Entrant
      - title: "High School"
        school:
          name: "Oberoi International School, Mumbai"
        GPA: "43/45"
        content: |-
          IBDP Program
            - Higher Level Subjects: Mathematics Analysis and Approaches, Physics, Chemistry
            - Standard Level Subjects: French, English Language and Literature, Economics
  
  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: FIRST Robotics Competition - Chairman's Award Finalist
        content: 2022-2023 season ~ Equivalent to being the No.2 overall team at the World Championships
      - title: FIRST Robotics Competition - Dean's List Finalist
        content: 2022-2023 season ~ Award for exceptional students in teams
      - title: FIRST Robotics Competition - Innovation Challenge Semi-Finalist
        content: 2022-2023 season ~ Designed a computer vision based home gym for Parkinson's Disease patients
  
    #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: I am always interested in talking to and learning from interesting people. My inbox is always open!
    email: rpunamiya6@gatech.edu
    btnName: Email me!
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
  
  footer:
    socialNetworks:
      github: https://github.com/ryanthecreator
      linkedin: https://www.linkedin.com/in/ryan-punamiya-47bb5a141/
      instagram: https://www.instagram.com/ryan.punamiya/

  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
